name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Build packages
        run: npx nx run-many --target=build --all
        shell: bash

      - name: Release and publish packages
        run: npx nx release --skip-publish
        shell: bash

      - name: Push release commit to GitHub
        run: |
          git push origin main
          git push --follow-tags
        shell: bash

      - name: Publish packages
        run: npx nx release publish --verbose
        shell: bash
